### ISSUE TITLE
Inline block code display issue

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#2322] opened 2021-10-01 19:31 UTC
**What happened**:
[This post](https://dev.to/pandanoxes/lab-3-merging-and-resolving-code-conflict-3304) is not being rendered correctly. 
The post contains a single line code 
 `` `Closed by <short_name_issue_code>.` `` in telescope it is render `<code>Closed by <short_name_issue_code>.</short_name_issue_code></code>`
 
![image](https://user-images.githubusercontent.com/58233223/135676272-27cafadf-ef33-4aae-83de-09b8e4292d7e.png)

**What should have happened**:
It should render `` `Closed by <short_name_issue_code>.` ``

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS: Windows 10
- Browser: Chrome Version 94.0.4606.61

**Comment by humphd** [comment] 2021-10-01 19:51
This is a possible duplicate of #1801, #2131, and #2313.  I think the solution to this is to fix [our `sanitize-html` logic](https://github.com/Seneca-CDOT/telescope/blob/124cf42e3e42a89c7181f6eadbbab40669c28aaa/src/backend/utils/html/sanitize.js) so that it [escapes vs. removes unknown HTML tags](https://github.com/apostrophecms/sanitize-html#what-if-i-want-disallowed-tags-to-be-escaped-rather-than-discarded).

The first step to solving this is add a failing test in https://github.com/Seneca-CDOT/telescope/blob/124cf42e3e42a89c7181f6eadbbab40669c28aaa/test/sanitize-html.test.js.  Something like:

```js
test('unknown tags should get escaped vs. removed', () => {
  const data = sanitizeHTML('<code>Closed by <short_name_issue_code>.</code>');
  expect(data).toBe('<code>Closed by &lt;short_name_issue_code&gt;.</code>');
});
```

@Kevan-Y has kindly offered to take up the torch and continue fighting this bug.

**Comment by Kevan-Y** [comment] 2021-10-05 14:42
The sanitize-html convert  tag like `<text>` into `<text></text>` (if adding disallowedTagsMode: 'escape' | 'recursiveEscape' to the config).
I tried to add the suggestion config from the related issue comment. None of those worked.
One solution I found is to convert every thing wrapped into <code> .( < will be &lt; > will be &gt;). Then pass to the sanitizeHtml() This way it will not procedure the issue above.

**Comment by humphd** [comment] 2021-10-05 14:55
I think we have a few bugs here, and your fix for adding `disallowedTagsMode: recursiveEscape` to the sanitizer might be a good start.  I think it would fix some of the cases we have in the linked issues (e.g., React components).  Do you want to create a PR just for that bit?

The second thing we should explore is what's happening in https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/html/replace-entities.js, which I suspect is also part of the problem here.

**Closed** 2021-10-30 01:51 UTC
Labels: type: bug
