### ISSUE TITLE
add test case for issue #22

### ISSUE THREAD

**Issue by dbeigi** [Seneca-CDOT/telescope#197] opened 2019-11-14 23:46 UTC
Need test cases for this issue #22

**Comment by jerryshueh** [comment] 2019-11-15 00:10
Thanks @dbeigi for opening this issue. To clarify, the inactive blog filter needs tests to verify it's actually returning properly for `update()` and `check()` functions. 

`check()` should return `false` if an item is **not** filtered (aka not listed in the redlist JSON), and `true` if it **is** redlisted.

`update()` parses the entire feeds list (from the text file, for now) using our feed-parser and checks whether or not the blog has been inactive for a certain amount of time (value is in .env). There are 3 scenarios:
* Feed is active (last post is within threshold)
* Feed is inactive (last post is older than threshold)
* Feed is dead (no posts or produces undefined data for whatever reason)
After running `update()`, the redlist JSON should be updated. We may need to create dummy blogs or alter the function to take dummy feed data to reproduce these conditions.

**Comment by Silvyre** [comment] 2019-11-15 03:27
Looking into this.

**Comment by Silvyre** [comment] 2019-11-15 19:51
Testing for `check()` was merged in #211.

As @jerryshueh mentioned, in order to produce proper testing for `update()`, we'll need to set up some testing conditions (e.g. a mock version of `feed-redlist.json`), or alter `update()`. If anyone has any ideas or suggestions regarding this, feel welcome to post them!

**Comment by jerryshueh** [comment] 2019-11-15 21:32
We _could_ pass `update()` the parsed JSON rather than the module reading the redlist itself. It was one of the things I debated, but in the end I decided to have the module handle everything because I wanted to blackbox it at the time. Also, since the parsing of feeds is asynchronous, the final JSON will not be the same each time, even if the URLs we pass are the same, because it all depends on the order the sync parsing happens. So rather than relying on the order of items in the file, we can only test whether a feed exists in the redlist at all. `check()` would be useful here, provided that it first passes successfully.

A method would be to change `update()` to receive the path to a JSON, with it taking the location of the operational redlist file by default (or better yet, take it from the .env). That way, if you _do_ pass it a filepath to some mock redlist, it will read from there instead. If you don't, it will default to the operational redlist JSON.

Just my two cents. If someone has more experience in developing for viable tests, please chime in!

**Comment by ImmutableBox** [comment] 2019-11-29 01:21
@Silvyre Hi, I also want to work on this issue. I just want to create a few tests for the `dateDiff` function to improve the coverage of `inactive-blog-filter`:

![image](https://user-images.githubusercontent.com/30512065/69837380-77695f00-121c-11ea-9db3-05dc85e32d27.png)

Is that ok?

**Comment by Silvyre** [comment] 2019-11-29 01:28
@ImmutableBox Certainly; please feel welcome to create tests to cover `dateDiff`. Thanks!

**Closed** 2019-12-02 02:58 UTC
Labels: type: test
