### ISSUE TITLE
optimize text-parser.js to use the same browser

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#423] opened 2019-12-03 08:15 UTC
The file `telescope/src/backend/utils/text-parser.js` needs to have its logic modified so it doesn't open a new browser window everytime the function is called.

Current state:
```
module.exports = async function(htmlFragment) {
  let browser;
  try {
    browser = await puppeteer.launch();
    const page = await browser.newPage();
  }
...
```
Target state: 
1. instantiate a browser instance to be used
2. use the same browser instance for all function calls
3. close the browser instance after all text parsing services have completed

**Comment by ThomasLuu00** [comment] 2019-12-03 18:58
Is there a reason we require a browser instance to parse the html text?

**Comment by humphd** [comment] 2019-12-03 19:33
@ThomasLuu00 they added it because JSDOM isn't able to do any text parsing that depends on layout information (i.e., you need a full browser to handle that).  They moved to Puppeteer to achieve this.

This bug is a dupe of #388, cc @sukhbeersingh.  I don't care who wants to fix this, but make sure you two co-ordinate, and close one of these.  @sukhbeersingh assigned this first, so I'd say he has right of first refusal.

**Comment by ragnarokatz** [comment] 2019-12-03 20:52
@humphd oops didn't see #388
Closing this ticket now and referencing the old ticket.

**Closed** 2019-12-03 20:53 UTC
Labels: area: back-end, duplicate
