### ISSUE TITLE
Site CRASH: "load more posts" in EMPTY search result

### ISSUE THREAD

**Issue by foxviet** [Seneca-CDOT/telescope#1420] opened 2020-11-19 21:53 UTC
When user try to search with keywords that returns no result, now it showing "load more posts" instead of showing something like "no result". When click on "load more posts" button, the web crash in ~20-30 secs.

![](https://i.imgur.com/oUKKK3y.jpg)

This one maybe relate to https://github.com/Seneca-CDOT/telescope/issues/1415, or sth else.

**Comment by humphd** [comment] 2020-11-19 22:53
Nice catch @VietnameZe.  Did I see a bug somewhere else to remove the "Load More Posts" button completely? cc @PedroFonsecaDEV.

**Comment by humphd** [comment] 2020-11-19 23:52
Steps To Reproduce:

1. Go to Search
1. Select Post as the filter
1. Type in `paul sinj` (or any text that doesn't exist in a post)
1. Click the LOAD MORE POSTS button
1. Open the DevTools Network tab
1. Watch it load page after page of non-results
1. Eventually it hits page 999, and on page 1000 returns a 400 and renders null (white screen)

<img width="1195" alt="Screen Shot 2020-11-19 at 6 50 46 PM" src="https://user-images.githubusercontent.com/427398/99738396-5dadd100-2a98-11eb-885e-4954466493cd.png">

cc @joelazwar

**Comment by joelazwar** [comment] 2020-11-20 08:36
Hmm yeah we need to code something to detect when it has all the results or else itll keep fetching at the bottom of the page. Working on something for #1408 that also might fix this

**Comment by DukeManh** [comment] 2021-02-14 02:05
I think I know what the cause is, `useSWRInfinite` returns an array of pages where `data[0]` is an array of posts on the first page. To determine if the research returns nothing we should check for empty `data[0]` rather than `data`  (`[ [] ]`) is truthy.

**Comment by DukeManh** [comment] 2021-02-14 02:17
I filed #1739, quick fix for this.

**Comment by PedroFonsecaDEV** [comment] 2021-02-14 02:18
> I filed #1739, quick fix for this.

Thanks @DukeManh. 
Please feel free to join us on Slack! You are more than welcome!

**Comment by DukeManh** [comment] 2021-02-14 02:19
I'm very happy to contribute. I already joined the server.

**Comment by DukeManh** [comment] 2021-02-14 04:52
The new properly rebased PR is #1742

**Closed** 2021-02-15 00:05 UTC
Labels: type: bug
