### ISSUE TITLE
Sporadic centering behaviour on new landing page

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#2087] opened 2021-04-06 13:59 UTC
During our triage meeting today, Dave was demoing the new landing page however as he scrolled down none of the content in the posts were centered.

I tried to replicate this but couldn't, though it can be seen during the meeting recording.

**Comment by chrispinkney** [comment] 2021-04-06 14:00
cc @PedroFonsecaDEV

**Comment by PedroFonsecaDEV** [comment] 2021-04-06 19:30
Ok. Investigating.

**Comment by PedroFonsecaDEV** [comment] 2021-04-06 19:54
Closing:
We could not reproduce the bug on different machines and browsers.
The behaviour is happening in only one isolated machine.

**Closed by PedroFonsecaDEV** 2021-04-06 19:54 UTC
Labels: area: front-end, type: bug
