### ISSUE TITLE
[next] Port DynamicImage/ to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1495] opened 2020-12-07 01:33 UTC
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/DynamicImage
**What would you like to be added**:
Port all components in DynamicBackgroundContainer/ to NextJS
**Why would you like this to be added**:
Porting reason

**Comment by sonechca** [comment] 2020-12-10 20:56
I want to take this issue. Can I join this one?
Thank you :)

**Comment by Metropass** [comment] 2021-01-27 15:44
Duplicate of #1492, it goes into more detail about porting the component

**Closed by Metropass** 2021-01-27 15:44 UTC
Labels: area: front-end, area: nextjs, type: enhancement
