### ISSUE TITLE
Contributor cards in dashboard doesn't show contributors' avatar

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#2961] opened 2022-02-17 14:13 UTC
**What happened**:

If the commit has >= 2 author, the card doesn't display contributors' avatar

![image](https://user-images.githubusercontent.com/58532267/154498416-f5085556-2f95-4cd8-990a-0c68c6cb6acb.png)

**What should have happened**:

It should display all avatars

**How to reproduce it (as precise as possible)**:

Whenever the commit has >= 2 authors like [this commit](8a76ffb3529edd022430278851da046430b2ea9f)

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by tcvan0707** [comment] 2022-02-17 14:22
I just want to confirm that it was just me or any one else. This issue just happens sometimes, not every time on my browser. I would tend to say it's not **STABLE**

**Comment by TueeNguyen** [comment] 2022-02-28 16:45
Currently working on staging, I can't figured out why it doesn't work in production. Any idea @nguyenhung15913?
![image](https://user-images.githubusercontent.com/58532267/156023083-048932c7-edd2-467a-a767-33117fa70e6c.png)

**Comment by manekenpix** [comment] 2022-02-28 23:56
I did some testing and this seems to be caused by not using a `github` token. We added support for `github` tokens, but we didn't add any. For testing, I created one for `staging` that will expire in a week (that's why it's working now), I think we can close this and reopen it if it keeps happening after adding tokens for both `staging` and `production`.

**Comment by nguyenhung15913** [comment] 2022-03-01 12:30
> Currently working on **staging**, I can't figured out why it doesn't work in production. Any idea @nguyenhung15913? ![image](https://user-images.githubusercontent.com/58532267/156023083-048932c7-edd2-467a-a767-33117fa70e6c.png)

Im stuck on that too. May be @manekenpix just gave us the reason

**Comment by tpmai22** [comment] 2022-03-07 02:19
@manekenpix have you have a chance to add `github` token for `production` at all ?

**Comment by manekenpix** [comment] 2022-03-07 04:02
@tpmai22 Adding it is not a problem, but I'm not sure if using personal tokens (in this case, a personal token created with my account) is a good idea.

**Comment by tpmai22** [comment] 2022-03-07 12:36
@manekenpix so is it good for us to get rid of the token ?

**Comment by humphd** [comment] 2022-03-10 13:21
@manekenpix let's follow-up on this.  I can't find a way to create anything other than a Personal Access Token.  I can use one of mine if you want to remove yours.

**Comment by manekenpix** [comment] 2022-03-10 23:17
@humphd  mine expired a couple of days ago, let me know when you're ready that new ones.

**Comment by humphd** [comment] 2022-03-11 00:46
I want to solve #2989 first, which I hope we'll do soon.

**Comment by tpmai22** [comment] 2022-03-11 17:53
Instead of closing this, I will move this to 2.9 so we got remind about this. But like what we disscussed with @humphd, the only way to solve this would be using PAT for this

**Comment by tcvan0707** [comment] 2022-04-08 16:01
Closed by PR #3430

**Closed by tcvan0707** 2022-04-08 16:01 UTC
Labels: type: bug, area: dashboard
