### ISSUE TITLE
Update About Us page with Telescope 3.0 features

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#3785] opened 2023-01-11 00:56 UTC
**Where is the problem?**
- [x] Screenshot

Simple fix, especially considering the running of the open source project class should be going on right now. Looks like the about us page is missing the features that was included last year with Telescope's 3.0 release. 

![Missing 3.0 feature documented](https://user-images.githubusercontent.com/16841702/211693139-87fb16f2-eb5f-4e8f-9400-42a4bc7ddc38.png)

**Comment by manekenpix** [comment] 2023-01-11 03:00
I think this is a duplicate of #3739. We should keep one of those, but not both. @HyperTHD can you take a look at #3739 and see which issue we should keep?

**Comment by HyperTHD** [comment] 2023-01-22 16:59
> I think this is a duplicate of #3739. We should keep one of those, but not both. @HyperTHD can you take a look at #3739 and see which issue we should keep?

Yup, that issue since it's more of a meta issue and can include other missing pages. This issue can be closed as a dupe

**Comment by manekenpix** [comment] 2023-01-23 16:57
Closing this in favour of #3739

**Closed by manekenpix** 2023-01-23 16:57 UTC
Labels: type: documentation (docs), good first issue, developer experience, 5 min fix, area: docusaurus
