### ISSUE TITLE
404 error when refresh 'Search page'

### ISSUE THREAD

**Issue by UsernameHasBeenChanged100Times** [Seneca-CDOT/telescope#1820] opened 2021-02-23 19:09 UTC
ONLINE 

Go to Search on https://dev.telescope.cdot.systems
Try refresh the page -> 404 error

LOCAL 
Do the same -> lose CSS for the search bar

- OS: Mac OS
- Browser: Chrome, Safari

**Comment by DukeManh** [comment] 2021-02-23 20:26
This issue might be a duplicate of #1795

**Closed** 2021-02-25 19:38 UTC
Labels: type: bug
