### ISSUE TITLE
CPU Pressure and Memory leak with useEffect() calls in main page

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#1018] opened 2020-04-16 01:05 UTC
**What happened**:
Youtube videos seem to be slowing down the system and causing massive lag spikes.  It looks it is causing mass memory leaks. 
**What should have happened**:
It shouldn't create a memory leak like this. 
**How to reproduce it (as precise as possible)**:
dev.telescope.cdot.systems and you can see how slow it goes and check console to see the memory application. 

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment] 2020-04-16 01:25
@raygervais has tested with https://github.com/Seneca-CDOT/telescope/commit/702138f2a5a2e839bbee5e303f826f204b8a5813 (1.0.0-alpha) and it doesn't seem to be affected.

**Comment by humphd** [comment] 2020-04-16 01:51
So the issue is something in https://github.com/Seneca-CDOT/telescope/compare/1.0.0-alpha...master.  The bug seems to be related to use loading and re-loading the posts over and over, and re-rendering the DOM, creating a ton of network traffic and memory thrashing.  The YouTube part isn't related, nor is the highlight.js stuff--they both just get triggered repeatedly.

**Comment by humphd** [comment] 2020-04-16 02:18
Traced to https://github.com/Seneca-CDOT/telescope/commit/f9a4c872a66b42f06fde99c6aa98c74099741e03, and an infinite render loop due to how we're doing `useEffect()`.  I've reverted for now in https://github.com/Seneca-CDOT/telescope/commit/4cd7ee80c2b4a41b316409e13382acf3193b9177, and we'll test on staging.

**Comment by humphd** [comment] 2020-04-16 02:26
Verified fixed on staging, closing.

**Closed** 2020-04-16 17:08 UTC
Labels: area: front-end, type: bug
