### ISSUE TITLE
Figues out why 304 got marked as `invalid`

### ISSUE THREAD

**Issue by tpmai22** [Seneca-CDOT/telescope#2604] opened 2021-12-13 19:23 UTC
**What happened**:
Refer to #2569 

The 304 show up as an invalid when it state that the content has not been modified yet and we would set `shouldDowload` to false 
https://github.com/Seneca-CDOT/telescope/blob/8b022875006add9b1b7f228ec1d47d58ba5f983b/src/backend/feed/processor.js#L76

After my debugging attempt it seem like the `304` get into the parser 
https://github.com/rbren/rss-parser/blob/33a9a4281d9c7aae051de148067223dcbdec5ad5/lib/parser.js#L87-L89

With my understand on the project, I will need more time to research and try different debugging technique to find it out

**What should have happened**:
`304` status code should not show up as invalid

**Comment by humphd** [comment] 2021-12-13 19:26
@tpmai22 I did a whole debugging session for you on Slack to look at why this is, can you include that info here for follow up?

**Comment by tpmai22** [comment] 2021-12-13 20:07
Debugging session and advices:

> run it locally or in gitpod, and change the feed list URL to point to something with only that one feed and set a breakpoint to watch it happen,  304 should be caught earlier and allowed
 
> set a breakpoint at https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/feed/processor.js#L143 to see why 304 doesn't stop the invalid feed going to the parser

> we might need to add `redirect:'follow'` to the `fetch()` at https://github.com/Seneca-CDOT/telescope/blob/8b022875006add9b1b7f228ec1d47d58ba5f983b/src/backend/feed/processor.js#L65

**Comment by humphd** [comment] 2022-01-30 14:44
Bumping this, as it's causing blogs from Tim, Anatoliy and others to not show on Telescope.  We need to prioritize getting this solved ASAP and ship a fix in 2.6.

**Comment by TDDR** [comment] 2022-01-30 15:22
I have spent some time on this with little progress. Here is a [thread in slack](https://seneca-open-source.slack.com/archives/CS5DGCAE5/p1642437293064200?thread_ts=1642433438.063900&cid=CS5DGCAE5) for some more context.

I'm not the best at using the Visual Studio Code debugger so I would be interested in maybe doing a [LiveShare](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) session, or just a old fashion screen share session if someone could help figure it out.

**Comment by humphd** [comment] 2022-01-30 22:15
> I have spent some time on this with little progress. Here is a [thread in slack](https://seneca-open-source.slack.com/archives/CS5DGCAE5/p1642437293064200?thread_ts=1642433438.063900&cid=CS5DGCAE5) for some more context.
> 
> I'm not the best at using the Visual Studio Code debugger so I would be interested in maybe doing a [LiveShare](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) session, or just a old fashion screen share session if someone could help figure it out.

cc'ing back-end folks @TueeNguyen, @nguyenhung15913, @tcvan0707, @AmasiaNalbandian, @joelazwar, @dbelokon, @JerryHue  + sheriffs @sirinoks, @aserputov.

Here's how I'd approach this debugging.

We have 2 blogs that we know are not going to Telescope:

```
[https://dps909tddr.tech.blog/category/opensource/feed/]
name=Tim Roberts

[https://medium.com/feed/@aserputov]
name=Anatoliy Serputov
```

1. I'd create a hacked-up local version of https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List#Feeds that only includes those two feeds, and change your `FEED_URL` env variable to point to this page.  OR, you could just hack https://github.com/Seneca-CDOT/telescope/blob/663b3c1da396ab080d03566eedd83532e4b21452/src/backend/utils/wiki-feed-parser.js#L29-L39 to always return an Array of Objects with those two feeds.  Either way, create a backend that only looks at these two feeds.

2. Either using the debugger, `logger`, or `console.log()`, add a bunch of logging to https://github.com/Seneca-CDOT/telescope/blob/663b3c1da396ab080d03566eedd83532e4b21452/src/backend/feed/processor.js#L121-L126.  I think the bug is that we somehow don't return from https://github.com/Seneca-CDOT/telescope/blob/663b3c1da396ab080d03566eedd83532e4b21452/src/backend/feed/processor.js#L142-L172 and end-up in https://github.com/Seneca-CDOT/telescope/blob/663b3c1da396ab080d03566eedd83532e4b21452/src/backend/feed/processor.js#L176-L192, which treats a 304 as an error.

3. Run the backend `npm start` and watch it fail.

4. Get on a Teams call early this week with a few people and try to reproduce this bug in GitPod or locally.  I love @TDDR's suggestion above about trying to work on it as a small group, since this isn't super easy to recreate and fix.

5. Let me know how you make out, and how I can help.

**Comment by humphd** [comment] 2022-02-01 22:49
I can't reproduce this bug locally.  I tried changing `src/backend/utils/wiki-feed-parser.js` to do this vs. download and read the planet feed list:

```js
module.exports = /* async */ function () {
  return Promise.resolve([
    {
      author: 'Tim',
      url: 'https://dps909tddr.tech.blog/category/opensource/feed/',
    },
  ]);
};
```

Then I set breakpoints in `src/backend/feed/processor.js`.

I deleted all the Redis data files in `./redis-data/*`

Then I ran Elasticsearch and Redis locally:

```
pnpm services:start redis elasticsearch
```

Next, I started the backend via VSCode's debugger, see [docs](https://github.com/Seneca-CDOT/telescope/blob/master/docs/debugging.md).

But I always get a 200.

**Comment by TueeNguyen** [comment] 2022-02-02 05:41
I've been trying to debug this but all I've got so far is 200 and occasionally 503. 

I let backend run with Tim's feed as the only feed to put Tim's feed into `Redis`. this `response` should return `status` 304 as the `etag` and `lastModified` weren't not null (pulled from Redis) but it didn't
https://github.com/Seneca-CDOT/telescope/blob/3311a26c9d0b8328c957f4906568425c325ff9a2/src/backend/feed/processor.js#L65

**Comment by humphd** [comment] 2022-02-02 13:28
Same for me (mostly 200s, a few 503s).

I'm going to close this as "not reproducible any more."  Thanks for looking into it with me.

I'll file another issue to wipe our Redis cache on staging/production, and free @TDDR's blog from the invalid queue.

**Closed by humphd** 2022-02-02 13:28 UTC
Labels: type: bug, area: back-end, Priority: High
