### ISSUE TITLE
Add Supabase development docker-compose file

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2877] opened 2022-02-10 18:00 UTC
Following on from #2876, we need to define a `development.yml` file for the Supabase containers, to define how to run the containers in development/CI vs. staging/production (production.yml).  There is actually something like this in `docker/supabase/dev/docker-compose.dev.yml`, which I don't think we need, but could use as a base.

This file can do things like open ports (8910, 8911) which we don't want on production, or override variables.

We'd then use this file in https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development#L18 at the end, to override things in the main Supabase docker-compose file.

**Comment by humphd** [comment] 2022-02-20 02:51
@sirinoks I watched some of your live stream tonight and saw you working on this for a bit.  I thought I'd add some context.

`docker-compose` lets you define a set of containers that you "compose" (i.e., run together).  The files are written in YAML, and the syntax is defined [here](https://docs.docker.com/compose/).

One thing that you can do with compose is to run multiple compose files at the same time, and later files can override earlier ones.  Your config files define the compose files that get run, for example in development we do [this](https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development#L18).

The Telescope stuff already does what we want, namely, it provides a base compose file `docker/docker-compose.yml`, and then we override aspects of it for development in `docker/development.yml`.  We want to do the same sort of thing for `docker/supabase/docker-compose.yml` (i.e., we want `docker/supabase/development.yml`).

We want to split up our definitions between those two files, with most of it going in `docker/supabase/docker-compose.yml`, and only a bit in `docker/supabase/development.yml` that is different.

Let me give you an example.  Consider the `image` microservice, which is defined in our main Telescope compose file here: https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L48-L73

This says where the `dockerfile` is located, what the build `context` directory is`, all the `environment` variables we pass in`, which other containers it `depends_on`, and any extra `labels` that we add (in this case, we pass config info to Traefik via labels).

Now, in `development.yml`, we don't do anything to override that stuff, see https://github.com/Seneca-CDOT/telescope/blob/master/docker/development.yml.  However, the `sso` service *does* get overrides here, to set different variables and dependent containers--but only in development: https://github.com/Seneca-CDOT/telescope/blob/master/docker/development.yml#L70-L76

Then, in `production.yml`, we override how the `image` service `restart`s when it crashes, here: https://github.com/Seneca-CDOT/telescope/blob/master/docker/production.yml#L87-L89. We only do this in production, not in development.

So using this technique, we can define a base container definition in `docker-compose.yml`, then modify it for dev or prod environments with overrides.

Here's a couple of things we could improve in https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/docker-compose.yml:

1. We are opening ports, for example https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/docker-compose.yml#L14-L15.  That's fine in development, but in production we'll get hacked.
2. We want containers to `restart` automatically in production, but not in development: https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/docker-compose.yml#L25

Let me know if you have more questions about this.  The best thing is to look at what we do in our Telescope docker-compose files (see `docker/`) and then use that as a guide for Supabase.

**Comment by TueeNguyen** [comment] 2022-03-28 22:38
Closing because the issue is no longer up to date. Exposing studio will be done in #2791 #3033 and we need `restart: unless-stopped` even in development mode

**Closed by TueeNguyen** 2022-03-28 22:38 UTC
Labels: type: enhancement, area: docker, area: supabase
