### ISSUE TITLE
Removing unnecessary console message in tests

### ISSUE THREAD

**Issue by evlnyng** [Seneca-CDOT/telescope#310] opened 2019-11-21 17:00 UTC
<img width="401" alt="Screen Shot 2019-11-21 at 11 58 02 AM" src="https://user-images.githubusercontent.com/34118418/69359329-68037800-0c56-11ea-9699-c8de181e81d3.png">

Pictured above.

**Comment by humphd** [comment] 2019-11-21 21:52
Duplicate of #244, closing both now that this is merged.

**Closed by humphd** 2019-11-21 21:52 UTC
