### ISSUE TITLE
Syntax highlighting problem [Dev.To] code block

### ISSUE THREAD

**Issue by huynguyez** [Seneca-CDOT/telescope#2220] opened 2021-04-28 17:45 UTC
This is on original blog post: https://dev.to/yuanleemidori/my-last-telescope-post-as-a-student-hopefully-5fg2 

![origin](https://user-images.githubusercontent.com/10421864/116449056-c22f4200-a827-11eb-80e1-2275db01681a.jpg)

### Chrome
![chrome](https://user-images.githubusercontent.com/10421864/116449094-cd826d80-a827-11eb-9014-af8b01cad296.jpg)

### FireFox:
![FF](https://user-images.githubusercontent.com/10421864/116449138-da06c600-a827-11eb-8cdd-2351f0b90c64.jpg)

### Safari:
![Safari](https://user-images.githubusercontent.com/10421864/116449163-e1c66a80-a827-11eb-8a5c-06e1bf6b6217.jpg)

(on mac os)

**Comment by humphd** [comment] 2021-04-28 18:32
Duplicate of https://github.com/Seneca-CDOT/telescope/issues/2131.  See also discussion in https://github.com/Seneca-CDOT/telescope/pull/2172.

**Closed** 2021-04-28 18:45 UTC
Labels: type: bug
