### ISSUE TITLE
Add Support for Dark Mode

### ISSUE THREAD

**Issue by jatinAroraGit** [Seneca-CDOT/telescope#222] opened 2019-11-15 21:22 UTC
Type: Feature Request
Area: Front-End

**Description**:
Add a feature to support dark theme throughout the UI of the website.

**Detail**: 

Many desktop and mobile application have now the functionality to enable dark mode/theme for the application.
It would be a nice thing to have as the Telescope project is meant for reading blogs and it with  a dark theme it can reduce the glare and blue light coming from the screen.
It will also help decreasing battery usage on devices with OLED or AMOLED displays.

I would like to take up this issue and work on it.

**Comment by humphd** [comment] 2019-11-16 05:02
Duplicate of https://github.com/Seneca-CDOT/telescope/issues/77

**Closed by humphd** 2019-11-16 05:02 UTC
Labels: area: front-end, type: enhancement
