### ISSUE TITLE
Discussion: Kubernetes

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#4] opened 2019-10-28 18:58 UTC
"Running on Seneca's [Kubernetes](https://kubernetes.io/) container cloud" is listed by [our overview document](https://github.com/Seneca-CDOT/telescope/blob/master/docs/overview.md) as one of the features required of Telescope to constitute a minimum viable product (MVP).

This issue exists to:
- aggregate research and useful information for those interested in contributing to this MVP feature. 
- discuss the directions we may take in implementing this feature.

_Importantly, research contributed to this thread will be referenced when we write documentation, which will be used by future contributors to our project. Therefore, by contributing to our research, you are also helping lay the groundwork for our project's documentation!_

Questions that have yet to be answered include:
1. As far as our project is concerned: what is Kubernetes, and what role will it play here?
1. How may we gain access to Seneca's Kubernetes container cloud? Who do we need to talk to?
1. Will the use of Kubernetes potentially affect [other MVP features](https://github.com/Seneca-CDOT/telescope/blob/master/docs/overview.md#mvp-features)?
1. Are there any security concerns that may come up when dealing with this feature?
1. Are there any standards or best practices that we should adhere to?
1. Should we create a 'Kubernetes' channel on the seneca-open-source Slack (e.g. to help facilitate open conversations), or should we keep all discussion on Kubernetes centralized within this GitHub issue?

**Currently, we have these tasks to do:**
  - [ ] Update documentation -------> (we have self documented files, but should make issue to have them on Documents)
  - [x] Add docker files to project
  - [ ] Adding Helm charts -------> (changd to raw YAML files)
  - [x] Deploy on Kubernetes
  - [x] Adding Health checks

**Comment by c3ho** [comment] 2019-10-29 16:46
@Silvyre Regarding 6. Perhaps we could use Kubernetes related tags for issues?

**Comment by Reza-Rajabi** [comment] 2019-11-03 02:25
I am also interested to work on this issue.

**Comment by Reza-Rajabi** [comment] 2019-11-04 13:56
My goal for this week is to make docker files and docker image.
I appreciate if anybody let me know if they have any comment on that.

**Comment by manekenpix** [comment] 2019-11-04 15:12
@Reza-Rajabi I've worked with docker before, we can work together on that.

**Comment by Reza-Rajabi** [comment] 2019-11-04 16:13
@manekenpix my pleasure. I am thinking of using the CloudNativeJs template for the Node.js, Express backend. What do you think about it?

**Comment by Silvyre** [comment] 2019-11-04 16:55
Sounds great! I'm interested in contributing a Makefile.

**Comment by manekenpix** [comment] 2019-11-05 00:42
@Reza-Rajabi I've never used CloudNativeJs but I think we can create our own ([check this out](https://docs.docker.com/get-started/part2/)). It'd be something like this:
```yaml
FROM node

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# Use a wildcard to ensure both package.json AND package-lock.json are copied
COPY ./package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Add config file(s)
RUN mkdir /usr/src/config-files
COPY ./config-files/file1 /usr/src/file1
COPY ./config-files/file2 /usr/src/file2

EXPOSE 80
CMD [ "npm", "start" ]
```

And then we could do something like [this](https://docs.docker.com/get-started/part3/) for deployment, and/or use [docker-compose](https://docs.docker.com/compose/).
Let me know what you think.

**Comment by Reza-Rajabi** [comment] 2019-11-05 01:43
That's it. [CloudNativeJs](https://github.com/CloudNativeJS/docker) only has ready temples for them. So if I am in the right way, would you like to let me make them, and would you mind reviewing them? How does that sound to you?

**Comment by Reza-Rajabi** [comment] 2019-11-05 01:58
@Silvyre I didn't think about it that way. The OS might don't matter for this case. I would like more of your thoughts.

**Comment by drwm-base** [comment] 2019-11-05 03:42
Hey guys, if were going to be using Redis, we should probably include it in the docker files? I don't know much about docker but in my research on Redis installation it seems a lot easier than installing it on your machine.

**Comment by humphd** [comment] 2019-11-05 03:43
See https://hub.docker.com/_/redis.  We can just pull existing images for it.

**Comment by Reza-Rajabi** [comment] 2019-11-07 03:02
@manekenpix @humphd  @Silvyre @c3ho @drwm-base  I have posted a [pull request](https://github.com/Seneca-CDOT/telescope/pull/65) regarding our Docker files, but I need help with a problem that I mentioned over there.

**Comment by Reza-Rajabi** [comment] 2019-11-07 06:02
Problem addressed by @manekenpix (thanks). I will make a docker-compose file soon.

**Comment by Reza-Rajabi** [comment] 2019-11-07 13:49
Docker files are waiting for review. Once it gets merged I will reflect these on Documents. Any thoughts about our next moves for this issue? Can I breakdown this to the following steps:

- adding Helm charts
- Deploy on Kubernetes
- Adding Health checks (self healing)

how does that sound?

**Comment by Silvyre** [comment] 2019-11-07 17:35
Fantastic @Reza-Rajabi!

I've found a Kubernetes-related blog post via Planet CDOT that I wanted to share: https://medium.com/@andrewvrosa/the-cdot-telescope-project-01-76b40317b6d7

Let's collect a Kubernetes-related blog posts, like these, within this thread!

**Comment by Reza-Rajabi** [comment] 2019-11-09 05:41
@Silvyre Thanks.

**Comment by Reza-Rajabi** [comment] 2019-11-09 05:43
> Docker files are waiting for review. Once it gets merged I will reflect these on Documents. Any thoughts about our next moves for this issue? Can I breakdown this to the following steps:
> 
> * adding Helm charts
> * Deploy on Kubernetes
> * Adding Health checks (self healing)
> 
> how does that sound?

I continue working on this issue as I listed above.

**Comment by manekenpix** [comment] 2019-11-09 05:52
Add the list to the first message, maybe something like:
- [x] Add docker files to project
- [ ] Add documentation about Docker (deployment, rebuilding containers...)
- [ ] Adding Helm charts
- [ ] Deploy on Kubernetes
- [ ] Adding Health checks

**Comment by Silvyre** [comment] 2019-11-09 05:54
Feel free to edit the original post to add tasks lists!

**Comment by wajeehsheikh** [comment] 2019-11-11 03:35
1. Did anyone push the telescope GitHub project to a repo on the Docker hub yet? 
2. Enable automated image builds and pushes to the registry, when new merges are approved?

If not, I would like to help with that.

**Comment by Reza-Rajabi** [comment] 2019-11-11 06:07
Hi @wajeehsheikh , 
Currently, @manekenpix, @Silvyre, and I are working on this issue based on the list at the beginning of these comments (the action plan at the bottom). I would be more than happy to have your help here as well. Here is the detail report of what we have so far from my point of view and my understanding:

What we have:
 - We have made Docker files for build and run locally. (sorry, but that's it right now :-) )

What do we need? Well, other than all listed in the action plan, we need to:
 - make docker files for development and debug environments
 - make docker files with a slim version of node for the run environment (more efficient deployment)
 - find a namespace (for Seneca maybe) on docker hub to put the image on rather than under any individual usernames
 - find a way to pass our environment variables in all docker files rather than hard coding them such as the currently exposed port number (as @humphd commented on his review on [here](https://github.com/Seneca-CDOT/telescope/pull/65#discussion_r344417273)
 - including all dependencies as required in docker files (so far we have Redis) if we need to

feel free to help with any part of the list at the top, help with the detailed list here, or give your suggestions and thoughts to improve or change them.
Thank you.

**Comment by wajeehsheikh** [comment] 2019-11-11 16:49
@Reza-Rajabi 
This is very helpful. 
I can start working on: 

- creating docker files for dev and debug environments.

- Creating an official Seneca account or using a current one on Docker hub to push the project on.

**Comment by Reza-Rajabi** [comment] 2019-11-11 19:45
I have used [CloudNativeJS](https://github.com/CloudNativeJS/docker) Docker templates for the one that we have now. You might find them helpful.

**Comment by Reza-Rajabi** [comment] 2019-11-13 17:01
@RyanWils Your pull request will close this issue since you have #4 in the title of your commit.

**Comment by Reza-Rajabi** [comment] 2019-11-17 12:50
@wajeehsheikh are you still working on these:

> * creating docker files for dev and debug environments.
> * Creating an official Seneca account or using a current one on Docker hub to push the project on.

**Comment by Reza-Rajabi** [comment] 2019-11-18 19:11
@wajeehsheikh I am wondering if I could have your feedback. Are you still working on this?

> @wajeehsheikh are you still working on this:
> 
> > * creating docker files for dev and debug environments.
> 
> I want to update our current docker file and I want to cover all environments in a single file. So if you didn't start please let me get it done. If you have started already please let me know how it is going.

**Comment by Reza-Rajabi** [comment] 2019-11-20 03:41
I am referencing #287 to not miss the comment

**Comment by Reza-Rajabi** [comment] 2019-11-21 02:46
@wajeehsheikh I am trying to send a pull request including docker file(s) for development, test and deployment. I am not sure yet if I better have them in a single file or two files. Please let me know if you are still working on the dev file. I will send them around the weekend if I don't have a chance to hearing from you.

**Comment by wajeehsheikh** [comment] 2019-11-24 19:30
@Reza-Rajabi I was going to start on them this week but if you're already done with the files. Send in the pull request. I will find another issue to work on.

**Comment by Reza-Rajabi** [comment] 2019-11-24 19:55
@wajeehsheikh I am almost done with the dev file, and I will be having a pull request tonight. I am so sorry; I messaged you two times since 7 days ago. I feel bad because of your message now. @humphd I am not sure if that's fair if I send a pull request.

**Comment by humphd** [comment] 2019-11-24 20:03
@Reza-Rajabi it sounds like @wajeehsheikh hadn't started on them yet, so no harm done.  I'm happy to help any and all of you find other things to work on.

@wajeehsheikh let me know if I can be helpful.

**Comment by Reza-Rajabi** [comment] 2019-11-24 20:07
Thanks @humphd @wajeehsheikh .

**Comment by Reza-Rajabi** [comment] 2019-11-25 05:56
@humphd @manekenpix @kartik-budhiraja 
There is one issue persists from the current (old) docker-compose file that I have stuck on, and I need help with that.
In the current docker-compose file in the telescope repo, we have the following line:
```
// line number 9
network_mode: host
//
```
This code is wrong and it causes the image to work as a host and not as a server, so there is not any exposed port as the result. we can inspect that if we run `docker ps` in CLI and having no port for the container. Because of this issue, the localhost is not accessible.
When I remove this line, the exposed port shows up so that we can see the UI in the localhost, but unfortunately, the Redis crashes.

My version (enhancment and adding SSO SAML2 tester):
![Screen Shot 2019-11-24 at 11 43 57 PM](https://user-images.githubusercontent.com/35855389/69513089-a5952900-0f14-11ea-81d8-86e75092a646.png)

The current (old) version:
![Screen Shot 2019-11-25 at 12 45 58 AM](https://user-images.githubusercontent.com/35855389/69515706-72a36300-0f1d-11ea-9c99-c7005d7c8018.png)

steps to reproduce:
- change the port number to the same port number as .env port number (8080:8080) In docker-compose file and also change the exposed port to the same in Dockerfile
- remove the line:  ` network_mode: host` from a docker-compose file (it is wrong and needs to be deleted)
- run in CLI: $ docker-compose up --build

Redis will crash.

I am not sure if something is wrong with the other parts of the code, or it is an issue with Redis misimplemented in the docker-compose file.

**Comment by Reza-Rajabi** [comment] 2019-11-25 13:11
It just came in my mind, it is not wrong. Because telescope is a host for redis. So it needs to be both host and server. Is that true?

**Comment by humphd** [comment] 2019-11-25 20:03
I'm not an expert on docker compose, but I don't think you need to specify a different network type, they should be able to discover and locate each other:

> By default Compose sets up a single network for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

We'd just need to make sure that we are setting the right host vs. container ports on the containers.

See the docs in https://docs.docker.com/compose/networking/

**Comment by wajeehsheikh** [comment] 2019-11-26 02:35
> @wajeehsheikh I am almost done with the dev file, and I will be having a pull request tonight. I am so sorry; I messaged you two times since 7 days ago. I feel bad because of your message now. @humphd I am not sure if that's fair if I send a pull request.

No worries. Im super busy myself with 6 courses and work so I dont want to slow you guys down. I cant blame you for wanting to get this project deployed and running asap. Good luck! :)

**Comment by Reza-Rajabi** [comment] 2019-12-03 13:37
@raygervais I will try to make a docker-compose draft and make a pre-pull request along with a deployment docker file. The docker-compose file may require a lot make up though afterward. How does that sound as a starting point? would you suggest any example for the docker-compose file?

**Comment by raygervais** [comment] 2019-12-03 15:46
@Reza-Rajabi, that's a great starting point. We can workout draft file together. Let me get back to you on that example, but if you have any ideas that you want to try please go ahead. You got this 😄

**Comment by Reza-Rajabi** [comment] 2019-12-07 23:52
@raygervais Hi. Sorry for the delay. I have made the drafts, so you might want to look into the pull request 👆and help to improve them.

**Comment by humphd** [comment] 2020-04-14 13:45
We're preparing to ship 1.0 later this week, and it will be based on docker-compose.  Post 1.0, figuring out a Kubernetes solution is still in scope.  However, I think we're going to need to start that discussion over again, from the perspective of where the project is when we decide to do it.

As such, I'm going to close this, our oldest (and dearest!) issue, and thank everyone who tried to push the Kubernetes rock up the hill.  We almost made it.

**Closed by humphd** 2020-04-14 13:45 UTC
Labels: area: back-end, area: docker, area: redis, question, type: discussion
