### ISSUE TITLE
Intermittent e2e failure: chromium running src/api/sso/test/e2e/signup-flow.test.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3504] opened 2022-04-18 19:17 UTC
This one test fails really often in CI.  It seems to happen with Chromium vs. Firefox/Webkit, and only for the `signup flow works to login and register a new Telescope user`:

```
FAIL browser: chromium src/api/sso/test/e2e/signup-flow.test.js (24.124 s)
  Signup Flow
    ✓ should have none of the users in the Users service for test data accounts (351 ms)
    ✕ signup flow works to login and register a new Telescope user (20173 ms)
    ✓ signup flow fails if user is not authenticated ([112](https://github.com/Seneca-CDOT/telescope/runs/6066997143?check_suite_focus=true#step:11:112) ms)
    ✓ signup flow fails if user data is missing required properties (855 ms)
    ✓ signup flow fails if user is already a Telescope user (623 ms)
    ✓ Signup flow fails if feed is already used by another Telescope user (1410 ms)

  ● Signup Flow › signup flow works to login and register a new Telescope user

    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      64 |     ensureUsers(users, false));
      65 |
    > 66 |   it('signup flow works to login and register a new Telescope user', async () => {
         |   ^
      67 |     // Part 1: login using SSO, as a user who does not have a Telescope account.
      68 |     // Confirm that the payload of the token we get back matches what we expect.
      69 |     // NOTE: the data comes from config/simplesamlphp-users.php.

      at src/api/sso/test/e2e/signup-flow.test.js:66:3
      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:46:1)
```

In the past @DukeManh has suggested we might try increasing the timeout from 20s to something longer, but I think @Kevan-Y might have tried this (please confirm).  We should figure this out and fix.

**Comment by Kevan-Y** [comment] 2022-04-18 20:01
It's falling in a different test case. 
Mine was `Login flow preserves state param`.
@JiaHua-Zou  was failing in `signup flow works to login and register a new Telescope user` which is this one, but his PR got fixed with my change. 

I tried before, increasing to 30s, but it didn't work.

**Comment by humphd** [comment] 2022-04-18 20:16
I added performance logging in https://github.com/Seneca-CDOT/telescope/runs/6067790391?check_suite_focus=true and of course it passes, but when it does, it takes less than 3 seconds to run this test, so I don't think it's just that it's slow.  Something else must be happening when it fails

```
console.log
    { ms: 12.20150999998441 } cleanupTelescopeUsers(users)

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:55:13)
          at runMicrotasks (<anonymous>)

  console.log
    { ms: 4.919407000008505 } browser.newContext()

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:59:13)

  console.log
    { ms: 393.33965500001796 } browser.newPage()

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:63:13)

  console.log
    { ms: 191.7720720000[215](https://github.com/Seneca-CDOT/telescope/runs/6067790391?check_suite_focus=true#step:11:215)8 } page.goto(`http://localhost:8888/auth.html`)

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:67:13)

  console.log
    { ms: 2913.719255999953 } partOne()

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:152:13)

  console.log
    { ms: 18.89476299996022 } partTwo(accessToken)

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:156:13)
          at runMicrotasks (<anonymous>)

  console.log
    { ms: 46.706865999964066 } partThree(feedUrls, accessToken)

      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:160:13)
          at runMicrotasks (<anonymous>)
```

**Comment by DukeManh** [comment] 2022-04-20 16:15
Another tests that often fails 
https://github.com/Seneca-CDOT/telescope/runs/6098161731?check_suite_focus=true

**Comment by humphd** [comment] 2022-04-20 17:15
That's same test failing with a 404:

```
 Signup Flow › signup flow works to login and register a new Telescope user

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 404

      100 |         body: JSON.stringify([blogUrl]),
      101 |       });
    > 102 |       expect(res.status).toBe(200);
          |                          ^
      103 |       const result = await res.json();
      104 |       expect(result).toEqual({
      105 |         feedUrls: [...galileoGalilei.feeds],

      at partTwo (src/api/sso/test/e2e/signup-flow.test.js:102:26)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:140:22)
```

Which is:

```js
    async function partTwo(accessToken) {
      // See the file blog.html in this same folder.  NOTE: the blog is hosted
      // on port 8888 running on the host, and the feed-discovery service needs
      // to access it via the test-web-content domain internally vs. localhost.
      const blogUrl = 'http://test-web-content/blog.html';

      const res = await fetch(FEED_DISCOVERY_URL, {
        method: 'POST',
        headers: {
          Authorization: `bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify([blogUrl]),
      });
      expect(res.status).toBe(200);     // <-------- 404
```

We [return a `404`](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/feed-discovery/src/router.js#L17) if we can't find any feed URLs for the given input:

```
    if (!(feedUrls && feedUrls.length)) {
      return res.status(404).json({ message: 'No feeds discovered' });
    }
```

**Comment by DukeManh** [comment] 2022-04-20 17:34
I am debugging this, the `Exceeded timeout of 20000 ms for a test` error only happens right after I start up the containers, once all containers have been running for a while, it can't be reproduced.

I suspect 1 one of the containers wasn't ready, and I think it's `test-web-content`. Like @humphd snippet shows above, the feed-discovery service is not able to find a feed from the hard-coded blog URL which is from `test-web-content`.

The `test-web-content` also has the `auth.html` to where, before each test, the browser has to navigate. I put a breakpoint into the failing test, but it's not reached because the test fails before the test is run.
Maybe we should investigate it.

**Comment by humphd** [comment] 2022-04-20 17:43
That's interesting, we could try to wait on the `test-web-content` being ready before we start, but the fact that it's not up after 20s is very odd.

**Comment by humphd** [comment] 2022-04-20 19:37
I added some code to dump docker logs when things fail in CI, and here is what I see.  Notice that something is hitting the server before the initialization has completed, which is sending back errors:

```
Run docker logs test-web-content
Notice: 20 19:12:16 [notice] 1#1: using the "epoll" event method
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
Notice: 20 19:12:16 [notice] 1#1: nginx/1.20.2
Notice: 20 19:12:16 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
Notice: 20 19:12:16 [notice] 1#1: OS: Linux 5.[13](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:13).0-1021-azure
Notice: 20 19:12:16 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
Notice: 20 19:12:16 [notice] 1#1: start worker processes
Notice: 20 19:12:16 [notice] 1#1: start worker process 32
Notice: 20 19:12:16 [notice] 1#1: start worker process 33
Error: /20 19:12:47 [error] 32#32: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:12:47 [error] 32#32: *2 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:08 [error] 32#32: *3 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:08 [error] 32#32: *4 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:09 [error] 32#32: *5 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:10 [error] 32#32: *6 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:18 [error] 32#32: *[14](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:14) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:19 [error] 32#32: *[15](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:15) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:19 [error] 32#32: *[16](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:16) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: [17](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:17)2.[18](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:18).0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 [19](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:19):13:19 [error] 32#32: *17 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /[20](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:20) 19:13:20 [error] 32#32: *18 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:22 [error] 32#32: *19 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:23 [error] 32#32: *20 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:24 [error] 32#32: *[21](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:21) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:25 [error] 32#32: *[22](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:22) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:26 [error] 32#32: *[23](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:23) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:27 [error] 32#32: *[24](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:24) open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:36 [error] 32#32: *36 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:37 [error] 32#32: *37 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:38 [error] 32#32: *38 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:39 [error] 32#32: *39 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
Error: /20 19:13:39 [error] 32#32: *40 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/auth.html"
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/[30](https://github.com/Seneca-CDOT/telescope/runs/6100975378?check_suite_focus=true#step:12:30)-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

**Comment by humphd** [comment] 2022-04-20 22:32
I can't make sense of this, despite spending a few hours digging through CI logs after failures.

**Closed** 2022-05-02 03:27 UTC
Labels: type: bug, area: CI/CD, type: test
